// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/about.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/countdown.tsx";
import * as $4 from "./routes/github/[username].tsx";
import * as $5 from "./routes/greet/[name].tsx";
import * as $6 from "./routes/html.tsx";
import * as $7 from "./routes/index.tsx";
import * as $8 from "./routes/plain.tsx";
import * as $9 from "./routes/search.tsx";
import * as $10 from "./routes/subscribe.tsx";
import * as $$0 from "./islands/Countdown.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/MyIsland.tsx";
import * as $$3 from "./islands/OtherIsland.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/about.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/countdown.tsx": $3,
    "./routes/github/[username].tsx": $4,
    "./routes/greet/[name].tsx": $5,
    "./routes/html.tsx": $6,
    "./routes/index.tsx": $7,
    "./routes/plain.tsx": $8,
    "./routes/search.tsx": $9,
    "./routes/subscribe.tsx": $10,
  },
  islands: {
    "./islands/Countdown.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/MyIsland.tsx": $$2,
    "./islands/OtherIsland.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
